title: Ivan The Scientist's Blog
description: >-
  My personal Blog.
baseurl: ""
url: "https://ivanthescientist.com"
github_username:  ivanthescientist

markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
